NAME = libft.a
FLAGS = -Wall -Wextra -Werror

SRC_DIR := ./libft/
OBJ_DIR := ./objs/

SRC := ft_memmove.c ft_strlcat.c ft_memset.c ft_strlen.c ft_atoi.c	ft_power_pos.c ft_strmap.c ft_bzero.c ft_putchar.c ft_strmapi.c ft_count_dig.c ft_putchar_fd.c ft_strncat.c ft_isalnum.c ft_putendl.c ft_strncmp.c ft_isalpha.c ft_putendl_fd.c ft_strncpy.c ft_isascii.c ft_putnbr.c ft_strnequ.c ft_isdigit.c ft_putnbr_fd.c ft_strnew.c ft_isprint.c ft_putstr.c ft_strnshift.c ft_itoa.c ft_putstr_fd.c ft_strnstr.c ft_lstadd.c ft_strcat.c ft_strrchr.c ft_lstdel.c ft_strchr.c ft_strshift.c ft_lstdelone.c ft_strclr.c ft_strshiftnot.c ft_lstiter.c ft_strcmp.c ft_strsplit.c ft_lstmap.c ft_strcpy.c ft_strstr.c ft_lstnew.c ft_strdel.c ft_strsub.c ft_memalloc.c ft_strdup.c ft_strtrim.c ft_memccpy.c ft_strequ.c ft_tolower.c ft_memchr.c ft_strinset.c ft_toupper.c ft_memcmp.c ft_striter.c ft_memcpy.c ft_striteri.c ft_memdel.c ft_strjoin.c ft_lst_reverse.c get_next_line.c ft_lstlen.c ft_lstdelnext.c ft_lstiter2.c

OBJ := $(addprefix $(OBJ_DIR), $(SRC:.c=.o))

all: $(NAME)

$(NAME): $(OBJ)
	ar rc $(NAME) $(OBJ)

$(OBJ_DIR)%.o: %.c
	@gcc -c $< -o $@

clean:
	@rm -f $(OBJ)
fclean: clean
	@rm -f $(NAME)
clean_all: clean
	@rm -f *~
re: fclean all

vpath %.c $(SRC_DIR)